name: Comment-based Cypress Trigger

on:
  issue_comment:
    types:
      - created

jobs:
  run-cypress:
    if: |
      github.event.issue.pull_request != null && contains(github.event.comment.body, '!cypress')
    uses: Loops-so/loops/.github/workflows/run-cypress-checks.yml@main
    with:
      ref: ${{ github.event.issue.pull_request.head.ref }}
