name: Comment-based Cypress Trigger

on:
  issue_comment:
    types: created

jobs:
  run-cypress:
    if: |
      github.event.issue.pull_request != null && contains(github.event.comment.body, 'run-cypress')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Debug Event Payload
        run: echo '${{ toJson(github.event) }}'
